cv/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
] + i18n_patterns(
    path('', include('main.urls')),
)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='main'),
    path('about/', views.About.as_view(), name='about'),
    path('experience/', views.Experience.as_view(), name='experience'),
    path('education/', views.Education.as_view(), name='education'),
    path('certificates/', views.CertificatesViews.as_view(), name='certificates'),
    path('certificates/<int:pk>', views.CertificatesDetailView.as_view(), name='detail'),
    path('skills/', views.LanguageView.as_view(), name='skills'),
    path('contacts/', views.MyContacts.as_view(), name='contacts'),
    path("set_language/<str:language>", views.set_language, name="set-language"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class PhotoProfile(models.Model):
    name = models.CharField(max_length=20, default='Данні профіля', verbose_name='Назва')
    profile_image = models.ImageField(upload_to='photo_profile/', verbose_name='Фото профіля')
    info = models.TextField(default='', verbose_name='Інформація')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Данні профіля'
        verbose_name_plural = "Про мене"

class PhotoDiploma(models.Model):
    title = models.CharField(max_length=255, default='', verbose_name='Назва Академії')
    diploma_image = models.ImageField(upload_to='photo_diploma/', verbose_name='Фото диплому')

    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name_plural = "Дипломи"

class DiplomaDescription(models.Model):
    title = models.CharField(max_length=255, default='', verbose_name='Назва')
    photo_diploma = models.ForeignKey(PhotoDiploma, on_delete=models.CASCADE, verbose_name='Назва Академії')

    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name = "Опис дипломів"
        verbose_name_plural = "Описи дипломів"

class Contact(models.Model):
    number_vodafone = models.CharField(max_length=20, verbose_name='Водафон')
    number_kyivstar = models.CharField(max_length=20, verbose_name='Київстар')
    email = models.EmailField(verbose_name='E-mail')
    linkedin = models.URLField(verbose_name='LinkedIn')
    telegram = models.URLField(verbose_name='Telegram')
    github = models.URLField(verbose_name='GitHub', default='')

    def __str__(self):
        return f'Контакти'
    
    class Meta:
        verbose_name_plural = "Контакти"

class Experience(models.Model):
    title = models.CharField(max_length=50, verbose_name='Роботодавець')
    year_work = models.CharField(max_length=20, verbose_name='Роки роботи')
    company_name = models.CharField(max_length=50, verbose_name='Назва компанії')
    position = models.CharField(max_length=50, verbose_name='Посада')
    responsibilities = models.TextField(verbose_name="Обов'язки")

    def __str__(self):
        return f'{self.company_name}'
    
    class Meta:
        verbose_name_plural = 'Досвід роботи'

class Education(models.Model):
    academy_name = models.CharField(max_length=100, verbose_name='Назва Академії')
    city_name = models.CharField(max_length=50, verbose_name='Місто')
    years_education = models.CharField(max_length=50, verbose_name='Роки навчання')
    profession = models.CharField(max_length=50, verbose_name='Професія')

    def __str__(self):
        return f'{self.academy_name}'

    class Meta:
        verbose_name_plural = 'Освіта'

class Language(models.Model):
    name_language = models.CharField(max_length=100, verbose_name='Мова програмування')
    icon = models.TextField(verbose_name='Іконка', default='')

    def __str__(self):
        return f'{self.name_language}'

    class Meta:
        verbose_name_plural = 'Мова програмування'

class Skills(models.Model):
    skill = models.CharField(max_length=100, verbose_name='Навик')
    progress = models.IntegerField(verbose_name='Прогрес', default=0, null=False)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, verbose_name='Мова програмування')

    def __str__(self):
        return f'{self.skill}'

    class Meta:
        verbose_name_plural = 'Навик'

main/forms.py
from django import forms
from django.core.validators import EmailValidator
from django.utils.translation import gettext_lazy as _

class ContactForm(forms.Form):
    name = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': _("Ім'я")}))
    email = forms.EmailField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Email"}) ,max_length=50, validators=[EmailValidator(message='Введено не коректний email')])
    subject_message = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': _("Тема")}))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}), max_length=2000)
    button = forms.CharField(label='', widget=forms.TextInput(attrs={'type':'submit', 'class':'btn btn-info', 'value': _('Надіслати'), 'style': 'width: 100%'}))

main/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView
from django.utils.translation import gettext as _
from .models import Contact, PhotoProfile, PhotoDiploma, DiplomaDescription, Experience, Education, Language, Skills
from .forms import ContactForm
from urllib.parse import urlparse
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls.base import resolve, reverse
from django.urls.exceptions import Resolver404
from django.utils import translation
from django.core.mail import send_mail
from django.utils.translation import gettext as _
from django.contrib import messages
from django.core.exceptions import ValidationError

def index(reqest):
    return render(reqest, 'index.html', {'title': _('Головна')})

class About(ListView):
    '''
    Про мене
    '''
    model = PhotoProfile
    template_name = 'about.html'
    context_object_name = 'contents'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Про мене')

        return context

class Experience(ListView):
    '''
    Досвід роботи
    '''
    model = Experience
    template_name = 'experience.html'
    context_object_name = 'works'
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Досвід роботи')

        return context

class Education(ListView):
    '''
    Освіта
    '''
    model = Education
    template_name = 'education.html'
    context_object_name = 'educations'
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Освіта')

        return context

class CertificatesViews(ListView):
    '''Відображення дипломів'''
    model = PhotoDiploma
    template_name = 'certificates.html'
    context_object_name = 'diplomas'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Дипломи')
        return context

class CertificatesDetailView(DetailView):
    model = PhotoDiploma
    template_name = 'certificates_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['descriptions'] = DiplomaDescription.objects.filter(photo_diploma=self.object)
        context['title'] = _('Пройдений матеріал')
        return context

class LanguageView(ListView):
    '''Навички'''
    model = Language
    template_name = 'skills.html'
    context_object_name = 'languages'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Навички')

        return context

class MyContacts(TemplateView):
    template_name = 'contacts.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Контакти')
        context['contents'] = Contact.objects.all()
        context['form'] = ContactForm()

        return context
    
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'].title()
            email = form.cleaned_data['email']
            message = f"Ім'я: {name}\nEmail: {email}\nПовідомлення: {form.cleaned_data['message']}"
            mail = send_mail(form.cleaned_data['subject_message'], message, 'sergeygrabar@gmail.com', ['serhiihrabar@ukr.net'], fail_silently=True)
            if mail:
                messages.success(request, _('Повідомлення надіслане'))
                send_mail('Дякую за відгук!!!', f'Дякую за відгук {name}. Я ціную вашу думку!', 'sergeygrabar@gmail.com', [f'{email}'])
                return redirect('contacts')
            else:
                messages.error(request, _('Помилка відправки'))
                return redirect('contacts')
        else:
            messages.error(request, _('Введено не коректний email'))
            return redirect('contacts')
                

#=====================================
def set_language(request, language):
    for lang, _ in settings.LANGUAGES:
        translation.activate(lang)
        try:
            view = resolve(urlparse(request.META.get("HTTP_REFERER")).path)
        except Resolver404:
            view = None
        if view:
            break
    if view:
        translation.activate(language)
        next_url = reverse(view.url_name, args=view.args, kwargs=view.kwargs)
        response = HttpResponseRedirect(next_url)
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
    else:
        response = HttpResponseRedirect("/")
    return response

main/templates/about.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}

    {% for content in contents %}
        <div class="row">
            <div class="col-xl-4 col-sm-4 col-xs-12 text-center about-div-one">
                <img class="rounded m-2" src="{{ content.profile_image.url }}" alt="" style="width: 12em; object-fit: cover; position: relative; z-index: 999;">
            </div>
            <div class="about-css col-xl-8 col-sm-8 col-xs-12 ps-3">
                <h1>{% trans 'Грабар Сергій' %}</h1>
                <h3>{% trans 'Python розробник' %}</h3>
                <h3 class="mt-3"><i class="bi bi-geo-alt"></i> {% trans 'Харків' %}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12 col-sm-12 col-xs-12 border-top border-bottom">
                <h3 class="hyphens">{{ content.info }}</h3>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

main/templates/certificates.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}
    <div id="carouselExample" class="pt-3 carousel slide">
        <div class="carousel-inner rounded-3">
            {% for diploma in diplomas %}
                <div class="rounded-3 p-5 carousel-item {% if forloop.first %}active{% endif %}">
                    <a class="text-decoration-none" href="{% url 'detail' diploma.pk %}">
                        <img src="{{ diploma.diploma_image.url }}" class="mx-auto d-block w-75 rounded" alt="...">
                        <p class="text-center text-white">{{ diploma.title }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
        <button class="hover-link carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="hover-link carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
    </div>
{% endblock content %}

main/templates/certificates_detail.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}
    <div class="row">
        <div class="col-xxl-6 col-md-12 col-xs-12">
            <img class="w-100 rounded" src="{{ object.diploma_image.url }}" alt="">
        </div>
        <div class="col-xxl-6 col-md-12 col-xs-12">
            <h3>{% trans 'Пройдений матеріал:' %}</h3>
            <ul>
                {% for description in descriptions %}
                    <li>{{ description.title }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <a class="btn btn-light mt-2" href="{% url 'certificates' %}">{% trans 'Назад' %}</a>
{% endblock content %}

main/templates/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% load i18n %}
    <div class="row">
        <div class="col-xs-12 col-md-6 col-xl-6">
            {% for content in contents %}
                <h4><i class="bi bi-telephone"></i> {{ content.number_vodafone }}</h4>
                <h4><i class="bi bi-telephone"></i> {{ content.number_kyivstar }}</h4>
                <h4><i class="bi bi-envelope"></i> {{ content.email }}</h4>
                <div class="row mt-3">
                    <div class="col-2">
                        <a class="social-network-link" href="{{ content.linkedin }}">
                            <p class="social-network">
                                <i class="logo-contacts bi bi-linkedin"></i>
                            </p> 
                        </a>
                    </div>
                    <div class="col-2">
                        <a class="social-network-link" href="{{ content.telegram }}">
                            <p class="social-network">
                                <i class="logo-contacts bi bi-telegram"></i>
                            </p> 
                        </a>
                    </div>
                    <div class="col-2">
                        <a class="social-network-link" href="{{ content.github }}">
                            <p class="social-network">
                                <i class="logo-contacts bi bi-github"></i>
                            </p> 
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mt-2 col-xs-12 col-md-6 col-xl-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <div>
                <form method="post">
                    <h4 class="text-center border rounded p-1 bg-white text-black">{% trans 'Залиште відгук' %}</h4>
                    {% csrf_token %}
                    <div class="row mb-2">
                        <div class="col-xs-12 col-md-6 col-xl-6 mb-2">
                            {{ form.name }}
                        </div>
                        <div class="col-xs-12 col-md-6 col-xl-6">
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12">
                            {{ form.subject_message }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mb-2">
                            {{ form.message }}
                        </div>
                    </div>
                    {{ form.button }}
                </form>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <div>
                <iframe class="rounded" style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d45428.69370304676!2d36223332166885874!3d4999036772412799!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f131!3m3!1m2!1s0x40dd40ad5a017737%3A0xe62258f160a8ee77!2sKharkiv%2C%20Kharkiv%20Oblast%2C%20Ukraine!5e0!3m2!1sen!2sus!4v1632962121364!5m2!1sen!2sus" width="100%" height="400" frameborder="0" allowfullscreen>
                </iframe>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/education.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}
    {% for education in educations %}
    <div class="row border rounded-3 p-3 m-1">
        <div class="col-lg-10 col-xs-12">
            <h4><i class="fa-solid fa-building-columns"></i> {{ education.academy_name }}</h4>
        </div>
        <div class="col-lg-2 col-xs-12">
            <h4><i class="fa-regular fa-calendar-days"></i> {{ education.years_education }}</h4>
        </div>
        <div class="col-12">
            <p><i class="bi bi-geo-alt-fill"></i>{{ education.city_name }}</p>
        </div>
        <div class="col-12">
            <p><i class="fa-solid fa-gears"></i> {{ education.profession }}</p>
        </div>
    </div>
    {% endfor %}
{% endblock content %}

main/templates/experience.html
{% extends 'base.html' %}

{% block content %}
    {% load i18n %}
    {% for work in works %}
        <div class="row border rounded-3 p-3 m-1">
            <div class="col-12">
                <h4>{{ work.year_work }}</h4>
            </div>
            <div class="col-12">
                <p>{{ work.company_name }}</p>
            </div>
            <div class="col-12">
                <h4>{{ work.position }}</h4>
            </div>
            <div class="col-12">
                <p class="hyphens">{{ work.responsibilities }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% load i18n %}
    <h1 class="text-center">{% trans 'Привіт, я Сергій Грабар' %}</h1>
    <h1 class="text-center">{% trans 'Python розробник' %}</h1>
    <div class="text-center index-style">
        <img class="index-img" src="{% static 'img/my_photo.png' %}" alt="">
    </div>
{% endblock content %}

main/templates/skills.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% load i18n %}
    <div class="accordion accordion-style" id="accordionExample">
        <div class="accordion-item bg-transparent text-white">
            {% for language in languages %}
                <h2 class="accordion-header" id="heading{{ language.id }}">
                    <button class="bg-button border-bottom hover-link accordion-button collapsed text-black" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ language.id }}" aria-expanded="false" aria-controls="collapse{{ language.id }}">
                        {{ language.icon|safe }} {{ language.name_language }}
                    </button>
                </h2>
                <div id="collapse{{ language.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ language.id }}" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        {% for skill in language.skills_set.all %}
                        <div class="row mb-2">
                            <div class="col-4 p-0">
                                <p class="m-0">{{ skill.skill }}</p>
                            </div>
                            <div class="col-8 p-0 d-flex align-items-center">
                                <div class="progress w-100">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: {{ skill.progress }}%;">
                                        <span class="progress-text">{{ skill.progress }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}